#Specify the ingress resource
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: citrix-ingress
  annotations:
   kubernetes.io/ingress.class: "citrix-ingress"
   ingress.citrix.com/secure-backend: "False"
   ingress.citrix.com/insecure-termination: "allow"
spec:
  tls:
  - secretName: cert-key
  rules:
  - host: citrix-ingress.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apache
          servicePort: 80
---
