# Default values for citrix-k8s-cpx-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: us.gcr.io/citrix-217108/citrix-k8s-cpx-ingress 
  tag: latest
  pullPolicy: Always
license:
  accept: no
ingressClass:  
exporter:
  require: 0
  image:
       repository: quay.io/citrix/netscaler-metrics-exporter
       tag: v1.0.0
       pullPolicy: Always
  ports:
       containerPort: 8888
