apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Citrix Ingress Controller configuring MPX/VPX 
name: citrix-k8s-ingress-controller
version: 1.1.1
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
maintainers:
- name: Priyanka Sharma
  email: priyanka.sharma@citrix.com
- name: Subash Dangal
  email: subash.dangol@citrix.com
