# Default values for citrix-k8-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/citrix/citrix-k8s-ingress-controller 
  tag: 1.1.1
  pullPolicy: Always 
loginFileName: nslogin1 #default secret file for NetScaler login
nsIP: x.x.x.x # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
logLevel: DEBUG 
license:
   accept: no #Should be 'yes' to run Citrix Ingress Controller
nsPort: 443 # Set port for NetScaler NITRO
nsProtocol: HTTPS #set protocol for NetScaler NITRO
logLevel: DEBUG
kubernetesURL:
ingressClass: 
exporter:
  require: 0
  image:
       repository: quay.io/citrix/netscaler-metrics-exporter
       tag: v1.0.0
       pullPolicy: Always
  ports:
       containerPort: 8888
